
# Disable specific steps - same options as the command line flag
disable = ["tlmgr", "node", "gem"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Cleanup temporary or old files
cleanup = true

# Custom commands
#[commands]
#"Python Environment" = "~/dev/.env/bin/pip install -i https://pypi.python.org/simple -U --upgrade-strategy eager jupyter"
