mklink /H %HOME%"\_vimrc" %HOME%"\.dotfiles\vimrc"
mklink /H %HOME%"\_gvimrc" %HOME%"\.dotfiles\gvimrc"
mklink /D %HOME%"\vimfiles" %HOME%"\.dotfiles\vim"
mklink /H %HOME%"\.bash_profile" %HOME%"\.dotfiles\bash_profile"
mklink /H %HOME%"\.bashrc" %HOME%"\.dotfiles\bashrc"
mklink /H %HOME%"\.localrc" %HOME%"\.dotfiles\msysrc"
mklink /H %HOME%"\.zshrc" %HOME%"\.dotfiles\zshrc"
mklink /H %HOME%"\.taskrc" %HOME%"\.dotfiles\taskrc"
mklink /H %HOME%"\.ackrc" %HOME%"\.dotfiles\ackrc"
mklink /H %HOME%"\.tmux.conf" %HOME%"\.dotfiles\tmux.conf"
mklink /D %HOME%"\Dropbox" %HOME%"\Documents\My Dropbox"
