tap homebrew/dupes
tap homebrew/science
tap phinze/cask
tap thoughtbot/formulae

install ack
install aria2
install imagemagick
install mosh
install rlwrap
install readline
install reattach-to-user-namespace
install tmux
install git
install tree
install optipng
install ssh-copy-id
install packer
install htop-osx
