tap "argoproj/tap"
tap "buo/cask-upgrade"
tap "cjbassi/gotop"
tap "derailed/k9s"
tap "derailed/popeye"
tap "go-task/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "kryptco/tap"
tap "minio/stable"
tap "nektos/tap"
tap "wagoodman/dive"

brew "ack"
brew "openssl"
brew "readline"
brew "sqlite"
brew "ansible"
brew "ansible-cmdb"
brew "ansible-lint"
brew "ant"
brew "aria2", restart_service: true
brew "assh"
brew "astyle"
brew "automake"
brew "azure-cli"
brew "bash"
brew "bitwarden-cli"
brew "black"
brew "blink1"
brew "boost"
brew "cheat"
brew "checkstyle"
brew "clipper", restart_service: true
brew "cmake"
brew "coreutils"
brew "ctags"
brew "ctop"
brew "curl"
brew "go"
brew "dep"
brew "devd"
brew "dfu-util"
brew "direnv"
brew "docker-completion"
brew "dos2unix"
brew "editorconfig"
brew "filebeat"
brew "findutils"
brew "flake8"
brew "fop"
brew "fpp"
brew "git"
brew "git-flow-avh"
brew "git-lfs"
brew "github-release"
brew "glances"
brew "glide"
brew "gnu-indent"
brew "pinentry"
brew "gnupg", link: false
brew "gost"
brew "gpg-agent"
brew "gradle"
brew "graphviz"
brew "grep"
brew "groovy"
brew "gstreamer"
brew "gst-plugins-base", link: false
brew "gst-libav"
brew "gst-plugins-bad"
brew "gst-plugins-good"
brew "gst-plugins-ugly"
brew "hadolint"
brew "kubernetes-helm"
brew "helmfile"
brew "howdoi"
brew "htop"
brew "hub"
brew "hugo"
brew "icdiff"
brew "imagemagick"
brew "iperf3"
brew "jfrog-cli-go"
brew "jmeter"
brew "jq"
brew "jsonlint"
brew "pandoc"
brew "jupyter"
brew "kompose"
brew "kubernetes-cli"
brew "kops"
brew "kubectx"
brew "kubernetes-service-catalog-client"
brew "libpcap"
brew "librsvg"
brew "logstash"
brew "macvim", args: ["HEAD"]
brew "mas"
brew "maven"
brew "md5sha1sum", link: false
brew "mitmproxy"
brew "mkcert"
brew "modd"
brew "mosh"
brew "most"
brew "mypy"
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "noti"
brew "opencv"
brew "socat"
brew "openshift-cli"
brew "optipng"
brew "packer"
brew "packer-completion"
brew "pbzip2"
brew "pigz"
brew "piknik"
brew "pinentry-mac"
brew "pipebench"
brew "platformio"
brew "postgresql"
brew "prettier"
brew "pulumi"
brew "rancher-cli"
brew "reattach-to-user-namespace"
brew "redis"
brew "restic"
brew "ripgrep"
brew "rlwrap"
brew "rsync"
brew "sassc"
brew "shellcheck"
brew "sqlparse"
brew "ssh-copy-id"
brew "sshuttle"
brew "sslscan"
brew "stern"
brew "telnet"
brew "terraform"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "tmux-xpanes"
brew "tmuxinator-completion"
brew "tree"
brew "truncate", link: false
brew "ttyd"
brew "unar"
brew "up"
brew "vault"
brew "velero"
brew "wget"
brew "yamllint"
brew "yank"
brew "yarn"
brew "ykpers"
brew "youtube-dl"
brew "yq"
brew "zopfli"
brew "zsh"

brew "argoproj/tap/argo"
brew "cjbassi/gotop/gotop"
brew "derailed/k9s/k9s"
brew "derailed/popeye/popeye"
brew "go-task/tap/go-task"
brew "kryptco/tap/kr"
brew "minio/stable/mc"
brew "nektos/tap/act"
brew "wagoodman/dive/dive"

cask "adium"
cask "appcleaner"
cask "arq"
cask "balenaetcher"
cask "basictex"
cask "bitwarden"
cask "docker"
cask "drawio"
cask "expandrive"
cask "fork"
cask "forklift"
cask "geekbench"
cask "github"
cask "gitscout"
cask "gitup"
cask "gpg-suite"
cask "imageoptim"
cask "insomnia"
cask "iterm2"
cask "java"
cask "jd-gui"
cask "keystore-explorer"
cask "macpass"
cask "microsoft-teams"
cask "mpv"
cask "paw"
cask "powershell"
cask "psequel"
cask "pullover"
cask "seafile-client"
cask "skim"
cask "skype"
cask "skype-for-business"
cask "ssh-tunnel-manager"
cask "tableflip"
cask "tex-live-utility"
cask "transmit"
cask "vagrant"
cask "vimr"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "vlc"
cask "xquartz"
cask "zerotier-one"

mas "Adafruit Bluefruit LE Connect", id: 1082414600
mas "Affinity Designer", id: 824171161
mas "Amphetamine", id: 937984704
mas "Apple Configurator 2", id: 1037126344
mas "Base", id: 402383384
mas "BreakTime", id: 427475982
mas "DaisyDisk", id: 411643860
mas "Deliveries", id: 924726344
mas "Disk Speed Test", id: 425264550
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "GIF Brewery 3", id: 1081413713
mas "Keynote", id: 409183694
mas "Marked 2", id: 890031187
mas "Microsoft Remote Desktop", id: 715768417
mas "MindNode", id: 1289197285
mas "Monodraw", id: 920404675
mas "Moom", id: 419330170
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Patterns", id: 429449079
mas "Pixave", id: 924891282
mas "Pixelmator", id: 407963104
mas "Reeder", id: 880001334
mas "Serial", id: 877615577
mas "Skitch", id: 425955336
mas "Slack", id: 803453959
mas "Soulver", id: 413965349
mas "SQLPro for Oracle", id: 1078273164
mas "SubnetCalc", id: 412946682
mas "Telegram", id: 747648890
mas "The Hit List", id: 432764806
mas "The Unarchiver", id: 425424353
mas "Tweetbot", id: 557168941
mas "WiFi Scanner", id: 411680127
mas "WiFi Signal", id: 525912054
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
mas "Xee³", id: 639764244
