#!/bin/sh
# Settings for using SQLplus

DYLD_LIBRARY_PATH="/opt/oracle/instantclient_10_2"
export DYLD_LIBRARY_PATH

TNS_ADMIN="/opt/oracle/tns"
export TNS_ADMIN

ORACLE_HOME="/opt/oracle/instantclient_10_2"
export ORACLE_HOME

alias sqlplus='/usr/local/bin/rlwrap /opt/oracle/instantclient_10_2/sqlplus'
