#!/usr/bin/env sh
# Work laptop specific settings

# Settings for using SQLplus
DYLD_LIBRARY_PATH="/opt/oracle/instantclient_10_2"
TNS_ADMIN="/opt/oracle/tns"
ORACLE_HOME="/opt/oracle/instantclient_10_2"

export DYLD_LIBRARY_PATH
export TNS_ADMIN
export ORACLE_HOME

alias sqlplus='/usr/local/bin/rlwrap /opt/oracle/instantclient_10_2/sqlplus'
