---

".vim/plug":
  type: "git-repo"
  url: "https://github.com/junegunn/vim-plug.git"
  refreshPeriod: "720h"
".tmux/oh-my-tmux":
  type: "git-repo"
  url: "https://github.com/gpakosz/.tmux.git"
  refreshPeriod: "720h"
".tmux/tpm":
  type: "git-repo"
  url: "https://github.com/tmux-plugins/tpm.git"
  refreshPeriod: "720h"
