#!/bin/bash

#
# OS Specific Settings
#
case $(uname) in
  (Darwin)
    export EDITOR='vim'
    export VISUAL='mvim -f'
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    [[ -d "/usr/local/bin" ]] && export PATH="/usr/local/bin:$PATH"                # Ensure /usr/local/bin is in path
    [[ -d "/opt/homebrew/bin" ]] && export PATH="/opt/homebrew/bin:$PATH"          # Ensure /opt/homebrew/bin is in path
    [[ -d "/opt/go" ]] && export GOPATH=/opt/go && export PATH="$PATH:/opt/go/bin" # GOPATH

    #
    # Aliases
    #
    alias flush-dns="sudo killall -HUP mDNSResponder"     # Flush DNS
    if [[ $TERM != "dumb" ]]; then
        [[ -d "/opt/oracle/client" ]] && alias sqlplus="DYLD_LIBRARY_PATH=/opt/oracle/client/lib /usr/local/bin/rlwrap -iIp red -f ~/.dotfiles/sql/sqlplus_completions -H ~/.sqlplus_history -s 30000 /opt/oracle/client/bin/sqlplus"
      else
        [[ -d "/opt/oracle/client" ]] && export DYLD_LIBRARY_PATH=/opt/oracle/client/lib && export PATH=$PATH:/opt/oracle/client/bin
    fi
  ;;
  (Linux)
    [[ $TERM == xterm ]] && export TERM="xterm-256color"
    export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD # Set colors for ls
    export PATH=$PATH:/sbin:/usr/sbin
  ;;
esac

[[ -d "${HOME}/.local/bin" ]] && export PATH="${HOME}/.local/bin:$PATH"                # Ensure ~/local/bin is in path

#
# Less
#
export LESS='-F -g -i -M -R -S -w -X -z-4'
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking-mode
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold-mode
export LESS_TERMCAP_me=$'\E[0m'           # end (blinking/bold)-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline
export LESS_TERMCAP_ue=$'\E[0m'           # end underline

#
# Aliases
#
alias clip="nc localhost 8377"
if hash piknik 2>/dev/null; then
  alias pkc='piknik -copy'
  alias pkp='piknik -paste'
  alias pkm='piknik -move'
  alias pkz='piknik -copy < /dev/null'
  alias pkpr='piknik -paste | tar xzhpvf -'
  function pko() {
      echo "$*" | piknik -copy
  }
  function pkf() {
      piknik -copy < "$1"
  }
  function pkfr() {
      tar czpvf - "${1:-.}" | piknik -copy
  }
fi

#
# Prompt
#

# Setup colors
if [[ $COLORTERM = gnome-* && $TERM = xterm ]]  && infocmp gnome-256color >/dev/null 2>&1; then TERM=gnome-256color; fi
if tput setaf 1 &> /dev/null; then
  tput sgr0
  if [[ $(tput colors) -ge 256 ]] 2>/dev/null; then
    BASE0=$(tput setaf 244)
    ORANGE=$(tput setaf 166)
    BLUE=$(tput setaf 33)
  else
    BASE0=$(tput setaf 12)
    ORANGE=$(tput setaf 9)
    BLUE=$(tput setaf 4)
  fi
  RESET=$(tput sgr0)
else
  ORANGE="\033[1;33m"
  RESET="\033[m"
fi

if [[ $TERM != "dumb" ]]; then
  # Set prompt based on whether the session is over SSH
  if [[ -n "$SSH_CLIENT" ]] || [[ -n "$SSH_TTY" ]]; then
    # SSH Session
    PS1="\[$BLUE\]☁ \[$BASE0\] \W\[$ORANGE\] ❯ \[$RESET\]"
    if [[ -t 0 ]]; then   # Only run if stdin is a terminal
      stty sane
    fi
  else
    # Local Session
    PS1="\[$BASE0\]\W\[$BASE0\]\[$ORANGE\] ❯ \[$RESET\]"
  fi
fi

#
# Local system specific settings
#
if [[ -f $HOME/.localrc ]]; then
  # shellcheck source=/dev/null
  source "${HOME}/.localrc"
fi
