#!/usr/bin/env zsh

###################
#  Path Settings  #
###################

typeset -gU path fpath
path=(
    $path
    /usr/local/{,s}bin(N-/)
    ${HOME}/.local/bin(N-/)
    ${HOME}/.local/bin/common(N-/)
)
fpath=(
    $fpath
    ${HOME}/.local/bin/common(N-/)
)

# Initialize zsh's completion system
if type brew &>/dev/null; then
  # Fix for homebrew installed zsh on Apple Silicon Macs
  fpath=("$(brew --prefix)/zsh/functions" $fpath)
  autoload -Uz compinit && compinit -u
else
  autoload -Uz +X compinit && compinit -u
fi

############################
#  Sheldon Initialization  #
############################

eval "$(sheldon source)"
