# https://example.com
#
# To build:
#   docker build --build-arg BUILD_ARG_ONE=${BUILD_ARG_ONE} BUILD_ARG_TWO=${BUILD_ARG_TWO} -t image-name .
#
# To run:
#   docker run --rm \
#     -it \
#     -v ${PWD}/config:/config:ro \
#     image-name

FROM alpine:latest

LABEL maintainer="JR Bing <jr@jrbing.com>" \
      base.image="alpine:latest" \
      version="1.0"

ARG BUILD_ARG_ONE
ARG BUILD_ARG_TWO

ENV BUILD_ARG_ONE=${BUILD_ARG_ONE} \
    BUILD_ARG_TWO=${BUILD_ARG_TWO}

VOLUME ["/some_directory"]

EXPOSE 80

RUN apk add --no-cache --update \
    curl \
    unzip \

####################
#  ContainerPilot  #
####################

ENV CONTAINERPILOT_VERSION 3.4.2

RUN export checksum=5c99ae9ede01e8fcb9b027b5b3cb0cfd8c0b8b88 \
    && curl -Lso /tmp/containerpilot.tar.gz \
         "https://github.com/joyent/containerpilot/releases/download/${CONTAINERPILOT_VERSION}/containerpilot-${CONTAINERPILOT_VERSION}.tar.gz" \
    && echo "${checksum}  /tmp/containerpilot.tar.gz" | sha1sum -c \
    && tar zxf /tmp/containerpilot.tar.gz -C /usr/local/bin \
    && rm /tmp/containerpilot.tar.gz

COPY containerpilot.json5 /etc/containerpilot.json5

##################
#  Consul Agent  #
##################

ENV CONSUL_VERSION 0.9.3

RUN export checksum=1884e8af16c07378aafe243554cf6d09478be074 \
    && curl -Lso /tmp/consul.zip \
         "https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip" \
    && echo "${checksum}  /tmp/consul.zip" | sha1sum -c \
    && unzip /tmp/consul.zip -d /usr/local/bin \
    && mkdir /var/opt/consul \
    && rm /tmp/consul.zip

# NOTE: Consul agent configuration is performed via command line parameters
#       in the containerpilot.json5 file

#############################################
#  Application specific build instructions  #
#############################################

COPY example.sh /example/

CMD /usr/local/bin/containerpilot -config /etc/containerpilot.json5
