" Remap the leader key
let mapleader = ","

" Set encoding
set encoding=utf-8

" Call pathogen
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

set nocompatible

set number
set ruler
syntax on

" Whitespace stuff
set nowrap
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set list listchars=tab:\ \ ,trail:·

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc
" set wildmenu

" Status bar
set laststatus=2

" Without setting this, ZoomWin restores windows in a way that causes
" equalalways behavior to be triggered the next time CommandT is used.
" This is likely a bludgeon to solve some other issue, but it works
set noequalalways

" NERDTree configuration
let NERDTreeIgnore=['\.rbc$', '\~$']
map <Leader>n :NERDTreeToggle<CR>

" Command-T configuration
let g:CommandTMaxHeight=20

" ZoomWin configuration
map <Leader><Leader> :ZoomWin<CR>

" CTags
map <Leader>rt :!ctags --extra=+f -R *<CR><CR>

" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

function! s:setupWrapping()
  set wrap
  set wm=2
  set textwidth=72
  set linebreak
  set nolist
  nnoremap j gj
  nnoremap k gk
  vnoremap j gj
  vnoremap k gk
  nnoremap <Down> gj
  nnoremap <Up> gk
  vnoremap <Down> gj
  vnoremap <Up> gk
  inoremap <Down> <C-o>gj
  inoremap <Up> <C-o>gk
endfunction

function! s:setupMarkup()
  call s:setupWrapping()
  " Change the tab settings to work properly with Pandoc lists
  set expandtab
  set tabstop=4
  set shiftwidth=4
  set softtabstop=4
  set textwidth=0
  set wrapmargin=0
  set formatoptions+=1
  set formatoptions+=n
  " Spellcheck
  " set spell
  set spelllang=en
  set spellsuggest=9 "show only 9 suggestions for misspelled words
  " Map the markdown preview to leader-p
  map <buffer> <Leader>p :Hammer <CR>
endfunction

" make and python use real tabs
au FileType make                                     set noexpandtab
au FileType python                                   set noexpandtab

" Thorfile, Rakefile and Gemfile are Ruby
au BufRead,BufNewFile {Gemfile,Rakefile,Thorfile,config.ru}    set ft=ruby

" md, markdown, and mk are markdown and define buffer-local preview
au BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn} call s:setupMarkup()

au BufRead,BufNewFile *.txt call s:setupWrapping()

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" load the plugin and indent settings for the detected filetype
filetype plugin indent on

" Opens an edit command with the path of the currently edited file filled in
" Normal mode: <Leader>e
map <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>

" Opens a tab edit command with the path of the currently edited file filled in
" Normal mode: <Leader>t
" map <Leader>te :tabe <C-R>=expand("%:p:h") . "/" <CR>

" Command mode: Ctrl+P
cmap <C-P> <C-R>=expand("%:p:h") . "/" <CR>

" Unimpaired configuration
" Bubble single lines
nmap <C-Up> [e
nmap <C-Down> ]e
" Bubble multiple lines
vmap <C-Up> [egv
vmap <C-Down> ]egv

" Use modeline overrides
set modeline
set modelines=10

if has ('gui_running')
" Default color scheme
  set background=dark
  " let g:solarized_contrast="low"    "default value is normal
  " let g:solarized_visibility="high"    "default value is low
else
  let g:solarized_termcolors=16
  set background=dark
endif
colorscheme solarized

" Set backup file location
set backupdir=~/.dotfiles/vim/backup
set directory=~/.dotfiles/vim/backup

" Highlight the current line
set cursorline

" Emulate the save on losing focus functionality that TextMate has
" au FocusLost * :wa

" Indentation
set autoindent

" Remap ,v to re-select text that was just pasted
nnoremap <leader>v V`]

" Have vim automatically reload the file in the buffer if the source file changes
set autoread

" Remap the help key to the escape key (since I'll be hitting it all the time)
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

" Remap ; to : to save the keystroke of having to hit shift all the time
nnoremap ; :
vnoremap ; :

" Map Ctrl+h,j,k,l to easily move around splits
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Remap easymotion keys
let g:EasyMotion_leader_key = '\'

" Remap key for command-t
nnoremap <silent> <A-t> :CommandT<CR>

" NERDTree
let NERDChristmasTree=1  "Makes NERDTree use colors
let NERDTreeChDirMode=1  "Changes the current working directory to the one set as the root in NERDTree
let NERDTreeShowBookmarks=1    "Display the bookmarks on startup

" Automatically reload the vimrc file when changed
autocmd BufWritePost ~/.dotfiles/vim/vimrc source $MYVIMRC

" Set par as the paragraph formatting program to use
set formatprg=par

" Settings for hammer.vim
" let g:HammerDirectory = $TEMP
" let g:HammerBrowser = 'chrome'
let g:HammerTemplate = 'merlin'

" Reassign mapping for quickbuf
let g:qb_hotkey = '<F8>'

