#!/usr/bin/env bash
# Usage: consigliere update
# Summary: Update dotfiles from github
# Help: Use this command to pull down the most recent copy of
# my dotfiles and update all submodules.

set -e

#Refresh dotfiles from repo and update submodules
cd ~/.dotfiles

# Pull down updates to dotfiles from github
printf 'Updating dotfiles from github...\n'
git pull origin master

# Update submodules
printf 'Updating plugins...\n'
git submodule update --init
