#!/usr/bin/env bash
# Usage: valet cheat <cheatsheet> (--list --edit)
# Summary: Displays the specified cheatsheet
# Help:

set -e

# Required program(s)
req_progs=(less git)
for p in ${req_progs[@]}; do
  hash "$p" 2>&- || \
  { printf >&2 " Required program \"$p\" not installed.\n"; exit 1; }
done

# Display usage if no parameters given
if [[ -z "$@" ]]; then
  valet help cheat
  exit
fi

# $# is the number of arguments
while [ $# -gt 0 ]
do
  case "$1" in
  (-e|--edit)
    local edit_flag="TRUE"
    shift;
  (-l|--list)
    local list_flag="TRUE"
    shift;
  (--)
    shift
    break;
  (*)
    break;
  esac
  shift
done
