#!/usr/bin/env bash
# Usage: valet update
# Summary: Update dotfiles from github
# Help: Use this command to pull down the most recent copy of
# my dotfiles, update rvm, and update homebrew

set -e

source $DOTFILES/share/valet/lib/liboutput.sh

#
# Pull down updates to dotfiles from Github
#
log 'Updating dotfiles from Github'
cd $DOTFILES && git pull origin master && git submodule sync && git submodule update --init --recursive
#git clean -dfx

#
# Update homebrew (if installed) and upgrade packages
#
if hash brew 2>/dev/null; then
  log "Updating homebrew repo, and upgrading installed packages"
  brew update && brew outdated && brew upgrade && brew cleanup
fi

#
# Update rvm (if installed)
#
if hash rvm 2>/dev/null; then
  log "Updating rvm"
  rvm get head
fi
