#!/usr/bin/env bash
# Usage: valet upgrade
# Summary: Upgrade installed software
# Help: Use this command to upgrade the installed software using the
# environments default package manager

set -e

# Source generic bash functions
source $DOTFILES/share/lib/bash-functions.sh

######################
# OS Specific Settings
######################

case $(uname) in
  (Darwin)
    # Update homebrew (if installed) and upgrade packages
    if hash brew 2>/dev/null; then
      echoinfo 'Updating homebrew repo'
      brew update
      echoinfo 'Outdated packages'
      brew outdated
      echoinfo 'Upgrading packages'
      brew upgrade
      echoinfo 'Cleaning up'
      brew cleanup
    fi
  ;;
  (Linux)
    # TODO: figure out how to do this for debian-based distros
    # Upgrade yum packages
    if hash yum 2>/dev/null; then
      echoinfo 'Updating yum packages'
      sudo yum upgrade -y
    fi
  ;;
  (SunOS)
    # TODO: add opencsw and pkgutil
  ;;
esac

#
# Update rvm (if installed)
#
if hash rvm 2>/dev/null; then
  echoinfo 'Updating rvm'
  rvm get head
fi

exit 0
