#!/usr/bin/env bash
# Usage: valet backup
# Summary: Runs the backup script
# Help: Run the backup my drive to the backup-server

# Set the script to exit immediately on error
set -e

# Source generic bash functions
source $DOTFILES/share/lib/bash-functions.sh

cd ~/Backup
backup perform -t backup
