#!/usr/bin/env bash
# Usage: valet cleanup
# Summary: Cleanup temporary files
# Help: Use this command to cleanup temporary files

# Set the script to exit immediately on error
set -e

cd ~/.dotfiles
git clean -dfx
