#!/usr/bin/env bash
# Usage: valet upgrade
# Summary: Upgrade installed software
# Help: Use this command to upgrade the installed software using the
# environments default package manager

set -e

# Source generic bash functions
source $DOTFILES/share/lib/bash-functions.sh

######################
# OS Specific Settings
######################

case $(uname) in
  (Darwin)
    # Update homebrew (if installed) and upgrade packages
    if hash brew 2>/dev/null; then
      echoinfo 'Updating OSX' && sudo softwareupdate -i -a
      echoinfo 'Updating homebrew repo' &&  brew update
      echoinfo 'Outdated packages' && brew outdated
      echoinfo 'Upgrading packages' && brew upgrade
      echoinfo 'Cleaning up' && brew cleanup
    fi
  ;;
  (Linux)
    #local os=$(lsb_release -si)
    if hash yum 2>/dev/null; then
      echoinfo 'Updating packages'
      sudo yum upgrade -y
    fi

    if hash aptitude 2>/dev/null; then
      echoinfo 'Updating packages'
      sudo aptitude upgrade -y
    fi
  ;;
  (SunOS)
    # TODO: add opencsw and pkgutil
  ;;
esac

exit 0
