#!/usr/bin/env bash
# Usage: valet update
# Summary: Update dotfiles from github
# Help: Use this command to pull down the most recent copy of
# my dotfiles

set -e

# Source generic bash functions
source $DOTFILES/share/lib/bash-functions.sh

#
# Pull down updates to dotfiles from Github
#
echoinfo 'Updating dotfiles'
cd $DOTFILES && git pull origin master && git submodule update --init --recursive
