#!/usr/bin/env bash
# Usage: valet maintenance
# Summary: Run OSX maintenance scripts
# Help: Use this command to run the daily, weekly, and monthly OSX maintenance
# scripts

set -e

source $DOTFILES/share/bsfl.sh

#
# Run the maintenance scripts
#
cmd "sudo periodic all"
