#!/usr/bin/env bash
# Usage: valet backup
# Summary: Runs the backup script
# Help: Run the backup my drive to the backup-server

# Set the script to exit immediately on error
set -e

cd ~/Backup
backup perform -t backup
