#!/usr/bin/env bash
# Usage: valet sync
# Summary: Runs the backup script
# Help: Backup my drive to the backup-server

# Set the script to exit immediately on error
set -e

# Source generic bash functions
source $DOTFILES/share/lib/bash-functions.sh

sync_directories=( Sync )

if [[ -d /Volumes/KEYCHAIN ]]; then
  for directory in ${sync_directories[@]}; do
    echoinfo "Synchronizing ${directory}"
    rsync --archive \
      --delete \
      --recursive \
      --progress \
      --whole-file \
      --exclude .SyncArchive \
      ~/$directory/ \
      /Volumes/KEYCHAIN/$directory/
  done
else
  echoerror "Keychain drive not found"
fi
