#!/usr/bin/env bash
# Usage:
# Summary:
# Help:

# Set the script to exit immediately on error
set -e

# Check if root
if [ $(whoami) != root ]; then
  echo " Must be root to use."
  exit
fi

usage(){
cat <<'EOT'
Call this script with...
EOT
exit 0;
}

# Exit if there are no arguments
[ $# -eq 0 ] && usage
set -- `getopt -n$0 -u -a --longoptions "help dogs: cats:" "hd:c:" "$@"`

# $# is the number of arguments
while [ $# -gt 0 ]
do
  case "$1" in
  -d|--dogs) dogs="$2"; shift;;
  -c|--cats) cats="$2"; shift;;
  -h|--help) usage;;
  --) shift;break;;
  *) break;;
  esac
  shift
done

cleanup_before_exit () {
  # this code is run before exit
  echo -e "Running cleanup code and exiting"
}
# trap catches the exit signal and runs the specified function
trap cleanup_before_exit EXIT

# OK now do stuff
echo "$cats and $dogs living together, mass hysteria!"

# Required program(s)
req_progs=(prog1 prog2)
for p in ${req_progs[@]}; do
  hash "$p" 2>&- || \
  { echo >&2 " Required program \"$p\" not installed."; exit 1; }
done

# Display usage if no parameters given
if [[ -z "$@" ]]; then
  echo " ${0##*/} <input> - description"
  exit
fi

# Text color variables
txtred='\e[0;31m'       # red
txtgrn='\e[0;32m'       # green
txtylw='\e[0;33m'       # yellow
txtblu='\e[0;34m'       # blue
txtpur='\e[0;35m'       # purple
txtcyn='\e[0;36m'       # cyan
txtwht='\e[0;37m'       # white
bldred='\e[1;31m'       # red    - Bold
bldgrn='\e[1;32m'       # green
bldylw='\e[1;33m'       # yellow
bldblu='\e[1;34m'       # blue
bldpur='\e[1;35m'       # purple
bldcyn='\e[1;36m'       # cyan
bldwht='\e[1;37m'       # white
txtund=$(tput sgr 0 1)  # Underline
txtbld=$(tput bold)     # Bold
txtrst='\e[0m'          # Text reset

# Feedback indicators
info=${bldwht}*${txtrst}
pass=${bldblu}*${txtrst}
warn=${bldred}!${txtrst}

# Indicator usage
echo -e "${info} "
echo -e "${pass} "
echo -e "${warn} "

