#!/usr/bin/env bash
# Usage: valet cleanup
# Summary: Cleanup temporary files
# Help: Use this command to cleanup temporary files

# Set the script to exit immediately on error
set -e

case $(uname) in
  (Darwin)
    # Update homebrew (if installed) and upgrade packages
    echoinfo 'Removing trash and temporary files'
    sudo rm -rfv /Volumes/*/.Trashes
    sudo rm -rfv ~/.Trash
    sudo rm -rfv /private/var/log/asl/*.asl
  ;;
  (Linux)
    # TODO
  ;;
  (SunOS)
    # TODO
  ;;
esac

exit 0
