#!/usr/bin/env bash
# Usage: valet maintenance
# Summary: Run OSX maintenance scripts
# Help: Use this command to run the daily, weekly, and monthly OSX maintenance
# scripts

set -e

#source $DOTFILES/share/valet/lib/liboutput.sh
source $DOTFILES/share/bsfl.sh

#
# Check if root
#
if [ $(whoami) != root ]; then
  log " Must be run as root. "
  exit
fi

#
# Run the maintenance scripts
#
periodic all
