#!/usr/bin/env bash
# Usage: valet update
# Summary: Update dotfiles from github
# Help: Use this command to pull down the most recent copy of
# my dotfiles and update all vim plugins

set -e

# Source generic bash functions
# shellcheck source=/dev/null
source "$DOTFILES/share/lib/bash-functions.sh"

function update_dotfiles() {
  start_spinner "Updating dotfiles"
  cd "$DOTFILES" \
    && git pull origin master > /dev/null 2>&1 \
    && git submodule update --init --recursive > /dev/null 2>&1
  stop_spinner $?
}

function cleanup_vim_plugins() {
  start_spinner "Cleaning unused vim plugins"
  vim +PlugClean! +qall > /dev/null 2>&1
  stop_spinner $?
}

function update_vim_plugins() {
  start_spinner "Updating vim plugins"
  vim +PlugUpdate +qall > /dev/null 2>&1
  stop_spinner $?
}

function update_asdf_plugins() {
  start_spinner "Updating asdf plugins"
  asdf plugin-update --all > /dev/null 2>&1
  stop_spinner $?
}

update_dotfiles
#cleanup_vim_plugins
#update_vim_plugins
update_asdf_plugins
