#!/usr/bin/env bash
# Usage: valet sync
# Summary: Runs the backup script
# Help: Backup files to keychain drive

# Set the script to exit immediately on error
set -e

# Source generic bash functions
source "$DOTFILES/share/lib/bash-functions.sh"

sync_directories=( BTS )

if [[ -d /Volumes/KEYCHAIN ]]; then
  for directory in "${sync_directories[@]}"; do
    echoinfo "Synchronizing ${directory}"
    rsync --archive \
      --delete \
      --recursive \
      --progress \
      --whole-file \
      --exclude .sync \
      ~/"$directory"/ \
      /Volumes/KEYCHAIN/"$directory"/
  done
else
  echoerror "Keychain drive not found"
fi
