#!/usr/bin/env bash
# Usage: valet upgrade
# Summary: Upgrade installed software
# Help: Use this command to upgrade the installed software using the
# environments default package manager

set -e

# Source generic bash functions
source $DOTFILES/share/lib/bash-functions.sh

case $(uname) in
  (Darwin)
    # Update homebrew (if installed) and upgrade packages
    if hash brew 2>/dev/null; then
      #(sudo softwareupdate -i -a) &
      #echoinfo 'Updating OSX' && spinner $!
      echoinfo 'Updating homebrew repo' && brew update
      echoinfo 'Outdated packages' && brew outdated
      echoinfo 'Upgrading packages' && brew upgrade
      echoinfo 'Cleaning up' && brew cleanup
    fi
    if hash rbenv 2>/dev/null; then
      echoinfo 'Updating rbenv' && rbenv update
    fi
    # Update vim plugins
    echoinfo 'Updating vim plugins'
    vim +BundleUpdate +qall
  ;;
  (Linux)
    if hash yum 2>/dev/null; then
      echoinfo 'Updating packages'
      sudo yum upgrade -y
    fi

    if hash aptitude 2>/dev/null; then
      echoinfo 'Updating packages'
      sudo aptitude upgrade -y
    fi

    # Update vim plugins
    echoinfo 'Updating vim plugins'
    vim +BundleUpdate +qall
  ;;
  (SunOS)
    # TODO: add opencsw and pkgutil
    echoinfo 'Updating packages'
    sudo pkgin update && sudo pkgin upgrade -y

    # Update vim plugins
    echoinfo 'Updating vim plugins'
    vim +BundleUpdate +qall
  ;;
esac

exit 0
