#!/usr/bin/env bash
# Usage: valet permfix <directory>
# Summary: Fixes directory permissions
# Help: Recursively changes the directory permissions to 755 at the specified
# path

set -e

# Source generic bash functions
source $DOTFILES/share/lib/bash-functions.sh

# Change the permissions at the specified directory
echoinfo "Modifying directory permissions on $1 to 755"
find $1 \! -perm 755 -type d -exec chmod 755 {} \;
