#
# Environment variables.
#

export DOTFILES=$HOME/.dotfiles

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  eval "$(locale)"
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# List of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ -d "$TMPDIR" ]]; then
  export TMPPREFIX="${TMPDIR%/}/zsh"
  if [[ ! -d "$TMPPREFIX" ]]; then
    mkdir -p "$TMPPREFIX"
  fi
fi

#
# OS Specific Settings
#

case $OSTYPE in
  (darwin*)
    source $DOTFILES/env/darwinrc
    eval "$($HOME/.dotfiles/bin/valet init -)"
  ;;
  (linux*)
    source $DOTFILES/env/linuxrc
    eval "$($HOME/.dotfiles/bin/valet init -)"
  ;;
  (solaris*)
    source $DOTFILES/env/solarisrc
  ;;
  (cygwin*)
    source $DOTFILES/env/msysrc
  ;;
esac

#
# Use .localrc for settings specific to one system
#

if [[ -f ~/.localrc ]]; then
  source ~/.localrc
fi
