#
# Environment variables.
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export DOTFILES=$HOME/.dotfiles

#
# OS Specific Settings
#

case $OSTYPE in
  (darwin*)
    eval "$("$HOME"/.dotfiles/bin/valet init -)"
    export JAVA_HOME=$(/usr/libexec/java_home)
    export EDITOR='vim'
    export VISUAL='mvim -f'
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    [[ -d "/opt/go" ]] && export GOPATH=/opt/go && export PATH="$PATH:/opt/go/bin" # GOPATH

    #
    # Aliases
    #
    alias z='fasd_cd -d'
    alias flush-dns="sudo discoveryutil udnsflushcaches"
    alias ans=ansible
    alias apb=ansible-playbook
    alias agx=ansible-galaxy
    alias anv=ansible-vault
    alias sqlplus="DYLD_LIBRARY_PATH=/opt/oracle/client/lib /usr/local/bin/rlwrap -iIp red -f ~/.dotfiles/sql/sqlplus_completions -H ~/.sqlplus_history -s 30000 /opt/oracle/client/bin/sqlplus"

  ;;
  (linux*)
    eval "$("$HOME"/.dotfiles/bin/valet init -)"
    export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD # Set colors for ls
    export PATH=$PATH:/sbin:/usr/sbin
  ;;
  (solaris*)
    export DISABLE_LS_COLORS=true
    export PATH=$PATH:/usr/cluster/bin
    export PATH=$PATH:/sbin
  ;;
  (cygwin*)
    alias vim="/c/Program\ Files/vim/vim74/gvim.exe &"
    alias exp="explorer"
  ;;
esac

#
# Use .localrc for settings specific to the local system
#

if [[ -f ~/.localrc ]]; then
  source ~/.localrc
fi
