#!/usr/bin/env bash

if [[ -s ~/.fig/shell/pre.sh ]]; then
  source ~/.fig/shell/pre.sh
fi

if [[ -f ~/.bashrc ]]; then
  source ~/.bashrc
fi

if [[ -s ~/.fig/fig.sh ]]; then
  source ~/.fig/fig.sh
fi
