[tools]
go = "latest"
node = "lts"
rust = "latest"
python = "latest"
ruby = "latest"

age = "latest"
aws-cli = "latest"
bats = "latest"
bun = "latest"
chezmoi = "latest"
dotenvx = "latest"
eza = "latest"
jq = "latest"
uv = "latest"
yazi = "latest"
shellcheck = "latest"
shfmt = "latest"

"github:d-kuro/gwq" = "latest"
"github:cli/cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python","ruby"]
