#!/usr/bin/env bash
# Settings specific to OSX

export JAVA_HOME=$(/usr/libexec/java_home)
export EDITOR='vim'
export VISUAL='mvim -f'
export LC_CTYPE="utf-8"

#
# Path
#
[[ -d "/usr/local/bin" ]] && export PATH=/usr/local/bin:$PATH # Workaround issue with PATH in yosemite
[[ -d "/opt/go" ]] && export GOPATH=/opt/go && export PATH="$PATH:/opt/go/bin" # GOPATH

#
# Aliases
#
alias z='fasd_cd -d'                              # Alias for FASD
alias flush-dns="sudo killall -HUP mDNSResponder" # DNS
alias ans=ansible
alias apb=ansible-playbook
alias agx=ansible-galaxy
alias anv=ansible-vault
alias sqlplus="export DYLD_LIBRARY_PATH=/opt/oracle/instantclient_11_2 ; /usr/local/bin/rlwrap -i -f ~/.sqlplus_history -H ~/.sqlplus_history -s 30000 /opt/oracle/instantclient_11_2/sqlplus"
