#!/bin/sh
#Settings specific for OSX

export PATH=/usr/local/bin:/usr/local/sbin:$PATH  # Necessary for homebrew
export JAVA_HOME=$(/usr/libexec/java_home)
export EDITOR='mvim'
export VISUAL='mvim -f'

[[ -d $DOTFILES/zsh/fasd ]] && export PATH="$DOTFILES/zsh/fasd:$PATH"                # Add fasd to PATH
[[ -d /usr/local/share/npm/bin ]] && export PATH="/usr/local/share/npm/bin:$PATH"    # Add npm bin to path if it exists
[[ -d /usr/local/share/python ]] && export PATH="/usr/local/share/python:$PATH"      # Add homebrew python scripts to path if it exists
[[ -d /usr/local/heroku ]] && export PATH="/usr/local/heroku/bin:$PATH"              # Heroku Toolbelt

alias z='fasd_cd -d' # Alias for FASD
