#!/usr/bin/env zsh
# Work laptop specific settings

# Settings for using SQLplus
export DYLD_LIBRARY_PATH="/opt/oracle/instantclient_10_2"
export TNS_ADMIN="/opt/oracle/tns"
export ORACLE_HOME="/opt/oracle/instantclient_10_2"
export SQLPATH="/Users/jbing/Dropbox/Code/psadmin-sql"
export JAVA_HOME=$(/usr/libexec/java_home)
export PATH=$JAVA_HOME/bin:$PATH
export PATH=/opt/oracle/swingbench/bin:$PATH

# Aliases
alias sqlplus='/usr/local/bin/rlwrap /opt/oracle/instantclient_10_2/sqlplus'
alias vim='mvim -v'
