-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")

-- Last location restore, resize, autosave on focus lost
-- augroup("miscellaneous", { clear = true })

-- autocmd("FocusLost", {
  -- group = "miscellaneous",
  -- pattern = "*",
  -- command = "silent! wall",
-- })
-- autocmd("VimResized", {
  -- group = "miscellaneous",
  -- pattern = "*",
  -- command = "wincmd =",
-- })

-- autocmd("BufReadPost", {
  -- group = "miscellaneous",
  -- pattern = "*",
  -- callback = function()
    -- local line = vim.fn.line "'\""
    -- if line > 0 and line <= vim.fn.line "$" then
      -- vim.cmd [[normal! g`"zvzz]]
    -- end
  -- end,
-- })
